version: "3.8"

services:
  web:
    image: ghcr.io/applied-cyber/ac-web:main
    ports:
      - "127.0.0.1:8080:80"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30